[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86-unknown-none.json"

[target.x86-unknown-none]
rustflags = ["-C", "link-arg=-Tlink.x"]
